### ISSUE TITLE
Geometry classes are not extensible

### ISSUE THREAD

**Issue by burasuk** [MatanYadaev/laravel-eloquent-spatial#62]
I want to change display results of coordinates, but for me returned  by Geometry class array is completely useless.
I want to return:

```
[
"latitude": 18.612053,
"longitude": 53.010963
]
```

How to do that?
I've try to extend Geometry class and add to casts, but i doesn't work.

**Comment by MatanYadaev** [comment]
@burasuk Hi, I can make the geometry classes extensible. Do you think it will be good enough to make the extension in the app-level? Meaning, if you'll create a new `Point` - every model in your app will use this new class. You won't be able to use multiple types of `Point` in different models.

**Comment by MatanYadaev** [comment]
@burasuk I implemented it, still in open PR. Let me know what you think about it, this is the docs: https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/02f6e2d7b366a4f05aa37c93809250bc06a6070c/README.md#extension

**Comment by affaron** [comment]
@MatanYadaev Firstly, thank you for creating this package, much appreciated!

And sorry for bumping this old issue, but maybe you have a suggestion how to return custom format specifically from toArray() to get it in serialized model? geojson format very inconvenient in my case.

Extending Point or other Geometry class isn't a solution because of all static::class checks. Macroable on the other hand doesn't allow to override methods, plus defining additional method and appending its value to every required model or using Resources is a pain and kills this magic of adding a simple cast. 

Do you have any other suggestions? I glanced over your initial solution with extending classes and yeah, it doesn't look elegant but it may provide a great benefit for the end users of the library. Thanks again

**Comment by MatanYadaev** [comment]
Hi @affaron. Making this package extensible via inheritance isn't simple and will require a big refactor and probably breaking changes. Unfortunately, I don't have time for this. :/

Can you please re-explain why macro doesn't work for you? Maybe I could try to improve it.

**Comment by affaron** [comment]
Hi @MatanYadaev. yeah, I see the issues with rewriting the package.

Sure, maybe you can suggest a better solution, appreciate your time.

See, macro can't override the default `toArray()` method that's used when models get serialized for the frontend. The only way to utilize that (as I see it) is to append an extra attribute with formatted data to each of our spatial models (actually, macro isn't needed for that). The problem is that we have a lot of these models, sometimes with multiple spatial columns and not every one of them has the same name throughout tables. It's doable for sure, but, overall, it's an extra place to take care of (both backend and frontend), especially when the spatial cast should theoretically take care of it all and format the data as we need.

Right now I forked your package and bluntly added toArray() method to the Point class with formatted data but it's more of a temporary solution until I find a way to make it better, by myself or with you help :)

Thanks!

**Comment by MatanYadaev** [comment]
@affaron For this I believe the geometry classes must be open for extension using OOP inheritance.
Unfortunately, I don't have time for this currently.

I will accept a PR that supports it. As I see it, it should introduce a new config file that sets geometry classes (point, linestring, etc), and uses these classes are used in the `Factory.php`.

I'll be happy to help if you have questions.

**Comment by MatanYadaev** [comment]
I created this WIP branch: https://github.com/MatanYadaev/laravel-eloquent-spatial/commits/geometries-extension
I won't have time to finish it soon, but I believe it's a good starting point.
